Upgrade version of Java
To address:

[2015-06-21 06:21:42,147][ERROR][bootstrap                ] Exception
java.lang.RuntimeException: Java version: 1.7.0_51 suffers from critical bug https://bugs.openjdk.java.net/browse/JDK-8024830 which can cause data corruption.
Please upgrade the JVM, see http://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html for current recommendations.
If you absolutely cannot upgrade, please add -XX:-UseSuperWord to the JVM_OPTS environment variable.
Upgrading is preferred, this workaround will result in degraded performance.
        at org.elasticsearch.bootstrap.JVMCheck.check(JVMCheck.java:121)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:211)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)